spring:
  application:
    name: account-service
uaa-service:
  url: http://101.200.43.126:8401
security:
  oauth2:
    resource:
      user-info-uri: ${uaa-service.url}/users/me
    client:
      clientId: account-service
      clientSecret: account@sec
      accessTokenUri: ${uaa-service.url}/oauth/token
      grant-type: client_credentials
      scope: server


